version = 1

[[annotations]]
path = [
 ".formatter.exs",
 ".gitignore",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Connor Rigby"
SPDX-License-Identifier = "CC-BY-4.0"
